title: Technical Bedrock Wiki
email: sirlich.business@gmail.com
description: >- 
  Technical Bedrock Wiki, written and maintained by SirLich#1658.

remote_theme: pmarsceill/just-the-docs

github_username:  SirLich

coderay_default_lang: JSON
markdown: kramdown

aux_links:
  "Discord":
    - "https://discord.gg/XjV87YN"
  "Bedrock.dev":
    - "https://bedrock.dev/"
  "Contribute":
    - "https://github.com/SirLich/technical-bedrock"
  "Beginner Guide":
    - "https://guide.bedrock.dev/"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: true
