title: Technical Bedrock
email: sirlich.business@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Technical Bedrock knowledge-base, written and maintained by SirLich.

remote_theme: pmarsceill/just-the-docs

baseurl: "/technical-bedrock/" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SirLich

coderay_default_lang: JSON
markdown: kramdown
# kramdown:
#   syntax_highlighter: rouge

aux_links:
  "Join the Discord":
    - "https://discord.gg/XjV87YN"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

