title: Technical Bedrock Wiki
email: sirlich.business@gmail.com
description: >- 
  Technical Bedrock knowledge-base, written and maintained by SirLich#1658.

remote_theme: pmarsceill/just-the-docs

github_username:  SirLich

coderay_default_lang: JSON
markdown: kramdown

aux_links:
  "Join the Discord":
    - "https://discord.gg/XjV87YN"
  "Visit Bedrock.dev":
    - "https://bedrock.dev/"
  "View the Repository":
    - "https://github.com/SirLich/technical-bedrock"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

